export const vehicles_data = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    type: "Sedan",
    chassis_no: "JT123ABC4567890",
    engine_no: "ENG98765432",
    reg_no: "ABC-1234",
    color: "White",
    purchase_date: "2020-05-15",
    price: 25000.0,
    purchase_order_no: "PO12345",
    fuel_capacity: 50.0,
    status: "unallotted",
  },
  {
    id: 2,
    make: "Ford",
    model: "F-150",
    type: "Truck",
    chassis_no: "FR456DEF7891234",
    engine_no: "ENG23456789",
    reg_no: "XYZ-5678",
    color: "Black",
    purchase_date: "2021-08-22",
    price: 45000.0,
    purchase_order_no: "PO12346",
    fuel_capacity: 80.0,
    status: "allotted",
  },
  {
    id: 3,
    make: "Honda",
    model: "Civic",
    type: "Sedan",
    chassis_no: "HN789GHI2345678",
    engine_no: "ENG34567890",
    reg_no: "LMN-9012",
    color: "Blue",
    purchase_date: "2019-03-11",
    price: 23000.0,
    purchase_order_no: "PO12347",
    fuel_capacity: 45.0,
    status: "unallotted",
  },
  {
    id: 4,
    make: "Tesla",
    model: "Model 3",
    type: "Electric",
    chassis_no: "TS234JKL9876543",
    engine_no: "ENG54321678",
    reg_no: "EV-1234",
    color: "Red",
    purchase_date: "2022-07-10",
    price: 50000.0,
    purchase_order_no: "PO12348",
    fuel_capacity: 0.0, // Electric Vehicle
    status: "allotted",
  },
];

export const allotment_data = [
  {
    id: 1,
    vehicle_id: 2,
    employee_id: 57,
    allotment_date: "2023-09-10",
    return_date: null, // Active allotment
    allotment_order_no: "A1234",
    approval_status: "approved",
    comments: "Assigned for project work.",
  },
  {
    id: 2,
    vehicle_id: 1,
    employee_id: 57,
    allotment_date: "2022-12-01",
    return_date: "2023-01-15", // Completed allotment
    allotment_order_no: "A1235",
    approval_status: "completed",
    comments: "Temporary allotment for site visit.",
  },
  {
    id: 3,
    vehicle_id: 1,
    employee_id: 42,
    allotment_date: "2023-08-05",
    return_date: null, // Active allotment
    allotment_order_no: "A1236",
    approval_status: "approved",
    comments: "Assigned for office commute.",
  },
  {
    id: 4,
    vehicle_id: 3,
    employee_id: 72,
    allotment_date: "2023-06-15",
    return_date: "2023-07-01", // Completed allotment
    allotment_order_no: "A1237",
    approval_status: "completed",
    comments: "Short-term assignment.",
  },
  {
    id: 5,
    vehicle_id: 4,
    employee_id: 61,
    allotment_date: "2023-10-01",
    return_date: null, // Active allotment
    allotment_order_no: "A1238",
    approval_status: "approved",
    comments: "Long-term allotment for CEO.",
  },
];

export const maintenance_data = [
  {
    id: 1,
    vehicle_id: 1,
    maintenance_date: "2023-06-01",
    description: "Oil change and tire rotation",
    cost: 150.0,
    service_center: "AutoCare Service Center",
  },
  {
    id: 2,
    vehicle_id: 3,
    maintenance_date: "2023-09-20",
    description: "Brake pad replacement",
    cost: 300.0,
    service_center: "QuickFix Garage",
  },
  {
    id: 3,
    vehicle_id: 2,
    maintenance_date: "2023-07-15",
    description: "Engine diagnostics and tuning",
    cost: 450.0,
    service_center: "HighTech Motors",
  },
  {
    id: 4,
    vehicle_id: 4,
    maintenance_date: "2023-10-05",
    description: "Battery health check and software update",
    cost: 200.0,
    service_center: "Tesla Service Center",
  },
];

export const logs_data = [
  {
    id: 1,
    vehicle_id: 2,
    log_date: "2023-09-11",
    start_odometer: 12000,
    end_odometer: 12250,
    distance_covered: 250,
    purpose: "Business trip to client site",
    driver_name: "John Doe",
    fuel_consumed: 20.0,
    comments: "Smooth ride, no issues.",
  },
  {
    id: 2,
    vehicle_id: 1,
    log_date: "2023-09-12",
    start_odometer: 35000,
    end_odometer: 35200,
    distance_covered: 200,
    purpose: "Project meeting in the city",
    driver_name: "Jane Smith",
    fuel_consumed: 15.0,
    comments: "Heavy traffic on the way back.",
  },
  {
    id: 3,
    vehicle_id: 3,
    log_date: "2023-08-30",
    start_odometer: 17500,
    end_odometer: 17800,
    distance_covered: 300,
    purpose: "Client visit out of town",
    driver_name: "Alice Green",
    fuel_consumed: 25.0,
    comments: "Good fuel efficiency on the highway.",
  },
  {
    id: 4,
    vehicle_id: 4,
    log_date: "2023-10-06",
    start_odometer: 1000,
    end_odometer: 1100,
    distance_covered: 100,
    purpose: "Test drive after software update",
    driver_name: "Tesla Engineer",
    fuel_consumed: 0.0, // Electric Vehicle
    comments: "No issues found during test drive.",
  },
];
